# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Differentiator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Differentiator

end

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
    pod 'RxSwift'
    pod 'RxCocoa'

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RxDataSources' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxDataSources

end
